title: <p align="center"> Tejas Kapasi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kapasitejas/">LinkedIn</a> |
  <a href="https://github.com/kapasitejas">GitHub</a>
  
  <br>   
  I am working as Sr. Engineer at Salesforce. I am certified Application and System Architect. I have 10 years of Salesforce Experience.
  I am exploring AI/ML content. 
  <br>
  </p>



theme: jekyll-theme-minimal
