title: <p align="center">Pat BALDOMAR</p>
logo: /assets/img/Paterno.jpg
description: 
  <p align="center">
  <a href="/another-page.html"><img alt="Static Badge" src="https://img.shields.io/badge/Entry%20Level%20Data%20Analyst-Data%20Science-green"></a>  
  <a href="https://in.linkedin.com/in/patab"><img alt="Static Badge" src="https://img.shields.io/badge/BIM%20CAD%20Designer-LinkedIn-blue"></a>
  <br>
  CONTACT INFORMATION
  <br>
  email ~ <a href="mailto:paterno.baldomar@gmail.com">paterno.baldomar@gmail.com</a>
  <br>
  phone ~ <a href="+639563723553">+63 956 372 3553</a>
  </p>
  <br>
  <p align="justify">
  Self-driven individual, always confident and eager to learn new thing. Independent yet collaborative in exchanging idea towards a common goal. Ability to connect effectively with other individuals. Creative and innovative with great analytical thinking.
  </p>
  </br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
